version: "3"
services:
 zookeeper:  # the configuration manager
   hostname: zookeeper:3.5
   container_name: zookeeper
   image: zookeeper:3.5
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
 nifi:
   image: apache/nifi:1.9.2
   ports:
     - 8181:8080 # Unsecured HTTP Web Port
   environment:
     - NIFI_WEB_HTTP_PORT=8080
     - NIFI_CLUSTER_IS_NODE=true
     - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
     - NIFI_ZK_CONNECT_STRING=zookeeper:2181
     - NIFI_ELECTION_MAX_WAIT=1 min
 nifi-registry:
   image: apache/nifi-registry:0.5.0
   ports:
     - 18080:18080